## model
model_config: 
  visual_dim: 1024
  bbox_entity_dim: 8
  bbox_so_dim: 5
  embd_dim: 512
  num_classes: 132
  backbone_arch: [2, 2, 3]
  scale_factor: 2
  fpn_start_level: 0
  max_seq_len: 96
  n_mha_win_size: 7
  use_abs_pe: False
  use_rel_pe: False
  use_local: False
  max_so_pair: 200
  fuse_ks: 1
  fuse_head: 4
  fuse_qx_stride: 1
  fuse_kv_stride: 1
  fuse_path_drop: 0.1
  n_head: 4
  embd_kernel_size: 3
  embd_with_ln: True
  dropattn: 0.0
  dropout: 0.0
  droppath: 0.1
  fpn_dim: 256
  fpn_with_ln: True
  fpn_norm_first: True
  loss_types: ['labels', 'masks']
  with_fuzzy: True
  scale_range: 0.85

  predictor:
    n_input: 512
    n_embd: 256
    n_head: 4
    n_hidden: 1024
    num_queries: 9
    num_classes: 132
    attn_pdrop: 0.0
    proj_pdrop: 0.0
    path_pdrop: 0.1
    cls_prior_prob: 0.01
    n_qx_stride: 0
    n_kv_stride: 1
    num_layers: 4
    deep_supervision: True
    enforce_input_project: False

  cost_coeff_dict:
    cost_class: 1.0
    cost_mask: 5.0
    cost_dice: 5.0

  loss_coeff_dict: 
    eos_coef: 0.1
    loss_class: 1.0
    loss_mask: 5.0
    loss_dice: 5.0

## data
dataset_config:
  ann_dir: "./datasets/vidvrd/annotations"
  info_dir: "./datasets/vidvrd/features/vidvrd_per_video_val"
  gt_boxfeatures_dir: "./datasets/vidvrd/features/GT_boxfeatures_training"
  test_boxfeatures_dir: "./datasets/vidvrd/features/Proposal_boxfeatures_test"
  cache_dir: './datasets/vidvrd/cache'
  cache_tag: "MEGA_mask"
  feat_stride: 1
  max_seq_len: 96

training_dataset_config:
  split: "train"
  cut_max_preds: True
  proposal_max_preds: 9
  num_pairs: 4

test_dataset_config:
  split: "test"
  proposal_min_frames: 2
  random_stride: False
  stride_offset: 0

## training
training_config:
  batch_size: 6
  training_epoch: 15
  total_epoch: 20
  training_lr: 0.0002
  seed: 42 
  num_workers: 4
  log_interval: 20
  save_interval: 1
  eval_start_epoch: 3
  clip_grad_l2norm: 1.0
  warmup: True
  warmup_epochs: 5
  type: "AdamW"
  momentum: 0.9
  weight_decay: 0.05
  schedule_type: "cosine"
  schedule_gamma: 0.1
  schedule_steps: [10]

## inf
inference_config:
  topk: 8
  feat_stride: 1
  pred_min_frames: 2
  n_max_pair: 200
  viou_th: 0.5

## gt
prepare_gt_config:
  gt_relations_path: "./datasets/vidvrd/vidvrd_val_gts.json"

  dataset_config:
    anno_rpath: "./datasets/vidvrd/annotations"
    video_rpath: "./datasets/vidvrd/videos"
    splits: ["test"]
